In [1]:
import tensorflow as tf
from tensorflow.contrib import learn
from sklearn.externals import joblib
import data_helpers
import numpy as np
import pandas as pd
import os
from NPDLogger import NPDLogger

In [2]:
model_path = '/temp0/dev/models/word2vec_cnn/'
training_data = '/temp0/dev/models/temp_file_videoscan_train_train.dat'

In [14]:
!ls -lrt /temp0/dev/models

total 7920072
-rw-r--r-- 1 aidev aidev    1150044 Feb  6 15:59 turgay_WM_input_records.dat
-rw-r--r-- 1 aidev aidev  192726845 Feb  6 15:59 turgay_WM_reference_data.dat
-rw-rw-r-- 1 aidev aidev    1142326 Feb  7 22:34 WM_input_records.dat
-rw-rw-r-- 1 aidev aidev  191127145 Feb  8 15:15 WM_reference_data_X.dat
drwxrwxr-x 2 aidev aidev       4096 Feb  8 15:15 word2vec_
-rw-rw-r-- 1 aidev aidev  322820082 Feb  9 00:01 US_reference_data_X.dat
-rw-rw-r-- 1 aidev aidev   55000000 Feb  9 00:01 US_reference_data_Y.dat
drwxrwxr-x 6 aidev aidev       4096 Feb 16 22:25 word2vec
-rw-rw-r-- 1 aidev aidev        931 Feb 17 14:32 industry_shortname_lookup.dat
drwxrwxr-x 2 aidev aidev       4096 Feb 24 01:08 word2vec_match
drwxrwxr-x 4 aidev aidev       4096 Mar 15 17:44 cnn_text
-rw-rw-r-- 1 aidev aidev 2789250379 Mar 17 12:31 temp_file5_macy.dat
-rw-rw-r-- 1 aidev aidev 4173529088 Mar 17 12:33 temp_file5_amazon.dat
-rw-rw-r-- 1 aidev aidev          0 Mar 18 15:23 temp_file5_macy_2_test.dat
-rw-rw-r

In [10]:
#! ls  /temp0/dev/models/word2vec_cnn/
def line_tokenize(Linelist=None):
        data_2dlist = []
        for i in xrange(len(Linelist)):
                data_2dlist.append(tf.compat.as_str(Linelist[i]).split())
        return data_2dlist


def Word2index2d(data_2dlist=None,dictionary=None):
        NewWord2index2d_inner = []
        NewWord2index2d = []
        for i in xrange(len(data_2dlist)):
                for j in xrange(len(data_2dlist[i])):
                        try: NewWord2index2d_inner.append(dictionary[data_2dlist[i][j]])
                        except: NewWord2index2d_inner.append(0)
                NewWord2index2d.append(NewWord2index2d_inner)
                NewWord2index2d_inner = []
        return NewWord2index2d


In [11]:
dictionary = joblib.load(model_path + '/dictionary.pkl')
embeddings = joblib.load(model_path + '/embeddings.pkl')

In [12]:
ss = tf.InteractiveSession()

Exception AssertionError: AssertionError("Nesting violated for default stack of <type 'weakref'> objects",) in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x2ba4990005d0>> ignored


In [13]:
ss.run(tf.cast(tf.nn.embedding_lookup(embeddings,dictionary["spiderm"]),tf.float16))

array([-0.14501953,  0.1529541 ,  0.32202148, -0.12744141,  0.17932129,
        0.01644897, -0.09558105, -0.15942383,  0.07507324,  0.07745361,
        0.07635498, -0.17663574,  0.20129395, -0.00812531,  0.10998535,
       -0.04302979, -0.02590942,  0.14440918, -0.06890869, -0.08502197,
        0.02037048, -0.00486755,  0.10266113, -0.02444458,  0.11676025,
       -0.03344727, -0.07342529,  0.22045898,  0.10626221,  0.07501221,
       -0.16479492, -0.02461243,  0.0602417 , -0.16491699, -0.10968018,
       -0.03613281,  0.13085938,  0.00397873, -0.11035156,  0.15014648,
        0.10290527,  0.03167725, -0.12103271, -0.16223145,  0.21826172,
        0.11328125, -0.04904175, -0.12487793,  0.10699463,  0.03210449,
       -0.1854248 ,  0.14331055,  0.0690918 , -0.04736328, -0.06939697,
       -0.03120422, -0.22290039, -0.19018555,  0.15673828,  0.05728149,
       -0.12976074, -0.02476501, -0.16821289, -0.20080566], dtype=float16)

dictionary

In [12]:
#dictionary
max_document_length  = 32

In [13]:
vocab_process = learn.preprocessing.VocabularyProcessor(max_document_length =max_document_length)

In [12]:
learn.preprocessing.VocabularyProcessor?

In [20]:
x_text_test, x_text_train, y = data_helpers.load_data_and_labels(training_data)
del x_text_test
del y

words_ = [tf.compat.as_str(x).split() for x in x_text_train]
words = [item for sublist in words_ for item in sublist]

In [21]:
np.array(list(vocab_process.fit_transform(x_text_train)))
#tf.nn.embedding_lookup(embeddings,dictionary[word])

array([[ 1,  2,  3, ...,  0,  0,  0],
       [ 1, 17, 14, ...,  0,  0,  0],
       [ 1,  2, 29, ...,  0,  0,  0],
       ..., 
       [38, 39, 14, ..., 28,  0,  0],
       [ 1, 17, 14, ...,  0,  0,  0],
       [ 1, 17, 14, ...,  0,  0,  0]])

In [74]:
len(dictionary)

43712

In [77]:
ss.run(tf.nn.embedding_lookup(embeddings,0))

array([-0.14276664,  0.13686794,  0.08431825,  0.04368779, -0.23479709,
        0.12103961, -0.20136392, -0.01855483, -0.13536727, -0.0738584 ,
        0.07063076,  0.21159935,  0.21945481, -0.00230686,  0.02664221,
        0.02548772,  0.18124405,  0.11112645, -0.03073082,  0.2362041 ,
       -0.17198046, -0.04571034, -0.35279286, -0.12136268,  0.15105487,
       -0.02880125,  0.04943464,  0.05526092,  0.04890934,  0.0867354 ,
        0.03599857, -0.05323701,  0.02578104,  0.04870079, -0.06361986,
       -0.05145854, -0.14232683,  0.07273249, -0.02789169, -0.0128205 ,
       -0.10631222,  0.39017111,  0.04733137,  0.05812557,  0.05407018,
        0.07828428,  0.06952811, -0.04604926, -0.10090795, -0.05623287,
       -0.11622163, -0.03263419,  0.09103311, -0.11683894,  0.07250867,
       -0.07022893, -0.1188589 , -0.19986254, -0.02853341,  0.17888133,
       -0.15916334, -0.03696275,  0.08363436, -0.01170939], dtype=float32)

In [83]:
len(dictionary)
#words

43712

In [1]:
embeddings.shape

NameError: name 'embeddings' is not defined

In [ ]:
new_emb =[]
for word in words:
    try: new_emb.append(ss.run(tf.nn.embedding_lookup(embeddings,dictionary[word])))
    except: new_emb.append(np.zeros(64))

In [22]:
len(vocab_process.vocabulary_)

56256

In [26]:
tf.constant(np.zeros(32))

<tf.Tensor 'Const:0' shape=(32,) dtype=float64>

In [34]:
ss.run(tf.concat(0,(tf.constant(np.zeros(10).reshape(5,2)),np.zeros(10).reshape(5,2))))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [65]:
#! /usr/bin/env python

import tensorflow as tf
import numpy as np
import pandas as pd
import os, sys
import time
import datetime
import data_helpers
from text_cnn import TextCNN
from tensorflow.contrib import learn
import csv
from sklearn.externals import joblib
from NPDLogger import NPDLogger

from subprocess import Popen, PIPE
#import os, sys, re,cx_Oracle, errno
# Parameters
# ==================================================
#timetamp = str(int(sys.argv[1]))



timetamp = '10000'
log_severity_level = 'debug'
log = NPDLogger(log_file_name='temp'+'_'+timetamp,log_severity_level = log_severity_level,console=True).log()
log.info("**** Program START *****************")
# Data Parameters
tf.flags.DEFINE_string("input_filename_train", "/temp0/dev/models/temp_file_videoscan_train_train.dat", "Data source input training items acting as reference.")
tf.flags.DEFINE_string("input_filename_test", "/temp0/dev/models/temp_file_videoscan_train_test.dat", "Data source input test items that will be matched to the reference embedded")

# Eval Parameters
#tf.flags.DEFINE_integer("batch_size", 64, "Batch Size (default: 64)")
tf.flags.DEFINE_string("checkpoint_dir", "/temp0/dev/models/word2vec_cnn/runs/"+timetamp+"/checkpoints", "Checkpoint directory from training run")
tf.flags.DEFINE_string("embed_input_dir", "/temp0/dev/models/word2vec_cnn/embed_input/"+timetamp+"/", "Save input intertms of embedding concat")
tf.flags.DEFINE_boolean("eval_train", True, "Evaluate on all training data")

# Misc Parameters
tf.flags.DEFINE_boolean("allow_soft_placement", True, "Allow device soft device placement")
tf.flags.DEFINE_boolean("log_device_placement", False, "Log placement of ops on devices")


FLAGS = tf.flags.FLAGS
FLAGS._parse_flags()
body = ""
print("\nParameters:")
for attr, value in sorted(FLAGS.__flags.items()):
	print("{}={}".format(attr.upper(), value))
	body = body + "{}={}".format(attr.upper(), value) + '\n'
	log.info("{}={}".format(attr.upper(), value))
print("")
if not os.path.exists(FLAGS.embed_input_dir):
	os.makedirs(FLAGS.embed_input_dir)
subject = "CNN_TEXT -" + timetamp
def send_mail(subject, body,email_recepients='anjani.sharma@npd.com'):
        read_msg = Popen(["echo", body], stdout=PIPE)
       	mail = Popen(["mail", "-s", subject, email_recepients], stdin=read_msg.stdout, stdout=PIPE)
	output = mail.communicate()[0]

def get_x_y(input_filename,data_type, nrows=0):
#input_names=['poiid','itemid','posoutlet','subcategoryn','brand','X_train','X_test']
    if data_type == 'train':
        input_names=['itemid','Y','X_train','X_test']
    else:
        input_names=['itemid','X_test']
    if nrows ==0:
        dt = pd.read_csv(input_filename,header=None,delimiter="|",error_bad_lines=0,names=input_names,quoting=3)
    else:
        dt = pd.read_csv(input_filename,header=None,delimiter="|",error_bad_lines=0,names=input_names,quoting=3,nrows = nrows)
    dt = dt.fillna('')
    if data_type == 'train':
        x_text = [data_helpers.clean_str(sent) for sent in dt.X_train.tolist()]
    else:
        x_text = [data_helpers.clean_str(sent) for sent in dt.X_test.tolist()]

    vocab_path = os.path.join(FLAGS.checkpoint_dir,"..", "vocab")
    vocab_processor = learn.preprocessing.VocabularyProcessor.restore(vocab_path)
    x = np.array(list(vocab_processor.transform(x_text)))
    y_itemid = dt['itemid'].astype(np.int32)
    log.info("%s ItemId Distinct count: %d" %(data_type,len(set(y_itemid))))
    y_subcategoryn = dt['itemid'].astype(np.int32)
    #log.info("%s Subcategory Distinct count: %d" %(data_type,len(set(y_subcategoryn))))
    return (x,y_itemid,y_subcategoryn)

def convert_from_embed_raw(x, pickle=False):
    embedding = joblib.load('/temp0/dev/models/word2vec_cnn/embeddings.pkl')
    vocab_size = embedding.shape[0]
    embedding_size = embedding.shape[1]
    checkpoint_file = tf.train.latest_checkpoint(FLAGS.checkpoint_dir)
    graph = tf.Graph()
    with graph.as_default():
        sess = tf.Session()
        with sess.as_default():
            saver = tf.train.import_meta_graph("{}.meta".format(checkpoint_file))
            saver.restore(sess, checkpoint_file)
            input_x = graph.get_operation_by_name("input_x").outputs[0]
            embedding_W = tf.placeholder(tf.float32, [vocab_size, embedding_size])
            embedded_chars = tf.nn.embedding_lookup(embedding_W, input_x)
            all_predictions = sess.run(embedded_chars, {input_x: x,embedding_W: embedding})
            print all_predictions.shape
            all_predictions = all_predictions.reshape(all_predictions.shape[0],all_predictions.shape[1]*all_predictions.shape[2])	
            print all_predictions.shape
            if pickle:
                joblib.dump(all_predictions, FLAGS.embed_input_dir + 'embedding_raw.pkl')
    return all_predictions


def convert_from_embed(x, pickle=False):
    checkpoint_file = tf.train.latest_checkpoint(FLAGS.checkpoint_dir)
    graph = tf.Graph()
    with graph.as_default():
        sess = tf.Session()
        with sess.as_default():
            saver = tf.train.import_meta_graph("{}.meta".format(checkpoint_file))
            saver.restore(sess, checkpoint_file)
            input_x = graph.get_operation_by_name("input_x").outputs[0]
            embedding_W = graph.get_operation_by_name("embedding/W").outputs[0]
            embedded_chars = tf.nn.embedding_lookup(embedding_W, input_x)
            all_predictions = sess.run(embedded_chars, {input_x: x})
            print all_predictions.shape
            all_predictions = all_predictions.reshape(all_predictions.shape[0],all_predictions.shape[1]*all_predictions.shape[2])	
            print all_predictions.shape
            if pickle:
                joblib.dump(all_predictions, FLAGS.embed_input_dir + 'embedding.pkl')
    return all_predictions

def convert_from_maxpool(x, pickle=False):
    checkpoint_file = tf.train.latest_checkpoint(FLAGS.checkpoint_dir)
    graph = tf.Graph()
    with graph.as_default():
        sess = tf.Session()
        with sess.as_default():
            saver = tf.train.import_meta_graph("{}.meta".format(checkpoint_file))
            saver.restore(sess, checkpoint_file)
            input_x = graph.get_operation_by_name("input_x").outputs[0]
            dropout_keep_prob = graph.get_operation_by_name("dropout_keep_prob").outputs[0]
            maxpool_drop = graph.get_operation_by_name("dropout/h_drop/mul_1").outputs[0]
            all_predictions = sess.run(maxpool_drop, {input_x: x,dropout_keep_prob: 1.0 })
            print all_predictions.shape
            if pickle:
                joblib.dump(all_predictions, FLAGS.embed_input_dir + 'maxpool.pkl')
    return all_predictions

#  Load raw files	
log.info("Running get_x_y - test")
#x, y_itemid,y_subcategoryn = get_x_y(input_filename=FLAGS.input_filename_test,data_type = 'test')
log.info("Running get_x_y - ref")
#x_train, y_train_itemid,y_train_subcategoryn = get_x_y(input_filename=FLAGS.input_filename_train, data_type = 'train')



   INFO [03/23/2017 05:00:59 PM] [<ipython-input-65-f13c877cee84> MainThread] [<module>] [27]: **** Program START *****************
INFO:/abinitio/dev/data/work/serial/ml_logs/temp_10000:**** Program START *****************


ArgumentError: argument --input_filename_train: conflicting option string(s): --input_filename_train

In [40]:
x[0]

array([  38,   39,   14,   40,   14,   41, 5325,  167,  168,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0])

In [38]:
y_itemid.shape

(29400,)

In [39]:
input_names=['itemid','Y','X_test']

(222900, 99)

In [3]:
input_names=['itemid','Y','X_train','X_test']

In [4]:
dt = pd.read_csv(training_data,header=None,delimiter="|",error_bad_lines=0,names=input_names,quoting=3)

In [10]:
dt.iloc[:10].X_test

0    ACNVideoScan-Historical First Alert    LITTLE ...
1    ACNVideoScan-Rovi   VIDEO BRAND MY BEST FRIEND...
2    ACNVideoScan-Historical US    TIGERS HOMETOWN ...
3    Amazon.com VIDEO MUSIC VIDEO & CONCERTS IMAGE ...
4           ACNVideoScan-Rovi   VIDEO BRAND FAIRY IDOL
5    ACNVideoScan-Historical First Alert    SNOWBER...
6    ACNVideoScan-Historical First Alert    GIRLS O...
7     ACNVideoScan-Rovi   VIDEO BRAND DESPERADO (1995)
8    ACNVideoScan-Historical Canada    STARSHIP TRO...
9    Amazon.com VIDEO MUSIC VIDEO & CONCERTS IMAGE ...
Name: X_test, dtype: object

In [9]:
dt.iloc[:10].X_train

0    ACNVideoScan-Historical First Alert    LITTLE ...
1    ACNVideoScan-Rovi   VIDEO BRAND MY BEST FRIEND...
2    ACNVideoScan-Historical US    TIGERS HOMETOWN ...
3    Amazon.com VIDEO MUSIC VIDEO & CONCERTS IMAGE ...
4    ACNVideoScan-Rovi   VIDEO BRAND FAIRY IDOL Chi...
5    ACNVideoScan-Historical First Alert    SNOWBER...
6    ACNVideoScan-Historical First Alert    GIRLS O...
7    ACNVideoScan-Rovi   VIDEO BRAND DESPERADO (199...
8    ACNVideoScan-Historical Canada    STARSHIP TRO...
9    Amazon.com VIDEO MUSIC VIDEO & CONCERTS IMAGE ...
Name: X_train, dtype: object

In [49]:
convert_from_embed_raw([x_train[0]])

(1, 99, 64)
(1, 6336)


array([[-0.13423242,  0.02163813,  0.31426671, ...,  0.11207271,
        -0.11200023,  0.00673293]], dtype=float32)

In [53]:
#convert_from_embed([x_train[0]])

KeyError: "The name 'embedding_1/W' refers to an Operation not in the graph."

In [63]:
def convert_from_embed(x, pickle=False):
    checkpoint_file = tf.train.latest_checkpoint(FLAGS.checkpoint_dir)
    graph = tf.Graph()
    with graph.as_default():
        sess = tf.Session()
        with sess.as_default():
            saver = tf.train.import_meta_graph("{}.meta".format(checkpoint_file))
            saver.restore(sess, checkpoint_file)
            input_x = graph.get_operation_by_name("input_x").outputs[0]
            embedding_W = graph.get_operation_by_name("embedding/W").outputs[0]
            embedded_chars = tf.nn.embedding_lookup(embedding_W, input_x)
            all_predictions = sess.run(embedded_chars, {input_x: x})
            print all_predictions.shape
            all_predictions = all_predictions.reshape(all_predictions.shape[0],all_predictions.shape[1]*all_predictions.shape[2])	
            print all_predictions.shape
            if pickle:
                joblib.dump(all_predictions, FLAGS.embed_input_dir + 'embedding.pkl')
    return all_predictions

In [64]:
convert_from_embed([x_train[0]])

NameError: global name 'FLAGS' is not defined